export const FEATURE_CATALOG = Object.freeze([
  {
    id: 'color-loss',
    area: 'learn',
    routeType: 'color-loss',
    icon: 'color-loss',
    accent: 'cyan',
    eyebrow: 'LIGHT + DEPTH',
    badge: 'INTERACTIVE LAB',
    title: 'Underwater Color Loss',
    summary: 'See which colors fade first as sunlight travels through water, then bring them back with a dive light.',
    shortSummary: 'See how depth changes the colors you see.',
    action: 'Start color-loss lab',
    featured: true,
  },
  {
    id: 'boyles-law',
    area: 'learn',
    routeType: 'boyles-law',
    icon: 'boyle',
    accent: 'gold',
    eyebrow: 'PRESSURE + VOLUME',
    badge: 'INTERACTIVE LAB',
    title: 'Boyle’s Law Lab',
    summary: 'Explore how pressure changes gas volume and why breathing gas is used faster as you descend.',
    shortSummary: 'Build intuition for pressure, volume, and gas use.',
    action: 'Start Boyle’s Law lab',
  },
  {
    id: 'gear-setup',
    area: 'learn',
    routeType: 'gear-setup',
    icon: 'gear',
    accent: 'good',
    eyebrow: 'ASSEMBLY',
    badge: 'INTERACTIVE LAB',
    title: 'Build a Scuba Unit',
    summary: 'Rig a cylinder, BCD, and regulator from parts — drag each piece together in the order you would on the dock.',
    shortSummary: 'Coming soon — assemble a scuba unit step by step.',
    action: 'Start gear-setup lab',
  },
  {
    id: 'compass-nav',
    area: 'learn',
    routeType: 'compass-nav',
    icon: 'compass',
    accent: 'cyan',
    eyebrow: 'NAVIGATION',
    badge: 'INTERACTIVE LAB',
    title: 'Compass Navigation',
    summary: 'Take a heading to a target, hold it level, and run a reciprocal course straight back — using your phone’s compass.',
    shortSummary: 'Take a heading, hold it, run a reciprocal.',
    action: 'Start compass lab',
  },
  {
    id: 'dive-computer-simulator',
    area: 'learn',
    routeType: 'dive-computer-simulator',
    icon: 'dive-computer',
    accent: 'cyan',
    eyebrow: 'DEPTH + TIME + DECOMPRESSION',
    badge: 'NATIVE SIMULATOR',
    title: 'Dive Computer Trainer',
    summary: 'Practice a recreational computer display, controlled ascents, safety stops, alarms, and decompression responses in guided scenarios.',
    shortSummary: 'Practice reading and responding to a rental-style dive computer.',
    action: 'Open computer trainer',
  },
  {
    id: 'dive-calculator',
    area: 'tools',
    routeType: 'calculator',
    icon: 'calculator',
    accent: 'good',
    eyebrow: 'PLANNING + GAS',
    badge: 'NATIVE TOOL',
    title: 'Dive Calculator',
    summary: 'Calculate pressure, Nitrox limits, tank blending, gas requirements, cylinder profiles, and Bühlmann tissue snapshots.',
    shortSummary: 'Planning, gas, blending, and decompression tools.',
    action: 'Open calculator',
  },
  {
    id: 'gear-checklist',
    area: 'tools',
    routeType: 'gear-checklist',
    icon: 'gear',
    accent: 'good',
    eyebrow: 'INVENTORY + READINESS',
    badge: 'NATIVE TOOL',
    title: 'Gear Locker',
    summary: 'Track equipment, service intervals, manuals, work orders, and reusable packing checklists for every kind of dive.',
    shortSummary: 'Inventory, service reminders, files, and reusable checklists.',
    action: 'Open gear locker',
  },
  {
    id: 'dive-log',
    area: 'tools',
    routeType: 'dive-log',
    icon: 'logbook',
    accent: 'cyan',
    eyebrow: 'DIVE HISTORY',
    badge: 'NATIVE TOOL',
    title: 'Logbook',
    summary: 'Record every dive with site, depth, time, gas, and conditions, then review your totals and history. Stored on this device.',
    shortSummary: 'Log your dives and track your totals.',
    action: 'Open logbook',
  },
  {
    id: 'dive-lens',
    area: 'tools',
    routeType: 'lens',
    icon: 'lens',
    accent: 'cyan',
    eyebrow: 'PHOTO IDENTIFICATION',
    badge: 'AI TOOL',
    title: 'Dive Lens',
    summary: 'Photograph or upload marine life or dive gear for an AI-assisted identification.',
    shortSummary: 'Identify marine life and dive gear from a photo.',
    action: 'Open Dive Lens',
  },
]);

export function getFeature(featureId) {
  return FEATURE_CATALOG.find((feature) => feature.id === featureId) || null;
}

export function getFeaturesByArea(area) {
  return FEATURE_CATALOG.filter((feature) => feature.area === area);
}

export function getFeaturedFeature() {
  return FEATURE_CATALOG.find((feature) => feature.featured) || FEATURE_CATALOG[0] || null;
}
