// Broad editorial exploration lenses. These are deliberately not species-range
// polygons: oceanRegionAt chooses the nearest lens so every ocean tap has useful
// context, while each card discloses that local conditions and wildlife vary.
export const OCEAN_REGIONS = [
  {
    id: 'caribbean', name: 'Caribbean Sea', shortName: 'Caribbean', subtitle: 'Coral reefs, mangroves & seagrass',
    latitude: 17, longitude: -75, zoom: 4, habitats: ['Coral reefs', 'Mangroves', 'Seagrass'],
    wildlife: ['Reef fish', 'Sea turtles', 'Sharks & rays', 'Marine mammals'],
    fact: 'NOAA describes the Caribbean as one of the Atlantic’s richest marine environments, with extensive reef and mangrove habitat.',
    story: 'Warm tropical shelves connect reef, seagrass and mangrove communities. Hurricanes, coral disease, bleaching and land-based pollution can change conditions sharply from place to place.',
    source: 'NOAA National Marine Ecosystem Status', url: 'https://ecowatch.noaa.gov/regions/caribbean',
  },
  {
    id: 'california-current', name: 'California Current', shortName: 'California Current', subtitle: 'Cold-water upwelling & giant migrations',
    latitude: 36, longitude: -126, zoom: 4, habitats: ['Kelp forests', 'Rocky reefs', 'Upwelling zones'],
    wildlife: ['Kelp communities', 'Sea lions', 'Whales', 'Pelagic fish'],
    fact: 'Seasonal upwelling brings cold, nutrient-rich water to the surface and fuels a highly productive food web.',
    story: 'Krill, anchovy and squid support larger fish, seabirds and marine mammals. Temperature, wind and El Niño cycles can move productive water and wildlife over large distances.',
    source: 'NOAA California Current IEA', url: 'https://www.integratedecosystemassessment.noaa.gov/regions/california-current',
  },
  {
    id: 'tropical-east-pacific', name: 'Tropical Eastern Pacific', shortName: 'East Pacific', subtitle: 'Seamounts, currents & pelagic life',
    latitude: 2, longitude: -105, zoom: 4, habitats: ['Oceanic islands', 'Seamounts', 'Open ocean'],
    wildlife: ['Hammerhead sharks', 'Manta rays', 'Tunas', 'Cetaceans'],
    fact: 'Islands and seamounts interrupt powerful currents, creating localized gathering and feeding areas in an otherwise open ocean.',
    story: 'This broad lens includes very different coastal and oceanic systems. Pelagic encounters depend strongly on current, productivity, depth and season; they are never guaranteed.',
    source: 'OBIS marine biodiversity network', url: 'https://portal.obis.org/',
  },
  {
    id: 'north-atlantic', name: 'North Atlantic', shortName: 'North Atlantic', subtitle: 'Shelves, canyons & cold-water coral',
    latitude: 46, longitude: -35, zoom: 3, habitats: ['Continental shelves', 'Submarine canyons', 'Cold-water coral'],
    wildlife: ['Whales', 'Sharks', 'Tunas', 'Deep-sea communities'],
    fact: 'Shelf edges, canyons and seamounts create eddies and upwelling that can concentrate plankton, fish and large predators.',
    story: 'The basin spans productive coastal shelves, the Gulf Stream system and deep ocean. A surface-temperature profile is useful regional context but says little about deep-water habitat.',
    source: 'NOAA Northeast Canyons & Seamounts', url: 'https://www.fisheries.noaa.gov/new-england-mid-atlantic/habitat-conservation/northeast-canyons-and-seamounts-marine-national',
  },
  {
    id: 'mediterranean', name: 'Mediterranean Sea', shortName: 'Mediterranean', subtitle: 'Seagrass, caves & endemic life',
    latitude: 37, longitude: 18, zoom: 5, habitats: ['Posidonia meadows', 'Rocky reefs', 'Caves & canyons'],
    wildlife: ['Groupers', 'Sea turtles', 'Cetaceans', 'Monk seals'],
    fact: 'UNEP reports more than 17,000 marine species, with an unusually high proportion found nowhere else.',
    story: 'Temperate and subtropical communities meet in a compact, heavily used sea. Seagrass, coralligenous reefs and underwater caves are especially important habitat.',
    source: 'UNEP Mediterranean Action Plan', url: 'https://www.unep.org/unepmap/resources/factsheets/biological-diversity',
  },
  {
    id: 'red-sea', name: 'Red Sea & Gulf of Aden', shortName: 'Red Sea', subtitle: 'Endemic reefs & desert coastlines',
    latitude: 20, longitude: 38.5, zoom: 5, habitats: ['Fringing reefs', 'Mangroves', 'Seagrass'],
    wildlife: ['Reef fish', 'Dugongs', 'Sea turtles', 'Pelagic sharks'],
    fact: 'UNEP highlights exceptional coral habitat, high fish endemism and more than 1,300 recorded fish species across the region.',
    story: 'Northern and central reefs contrast with the nutrient-rich Gulf of Aden. Heat tolerance, endemism and strong north–south gradients make local context especially important.',
    source: 'UNEP Jeddah Convention / PERSGA', url: 'https://www.unep.org/jeddah-convention',
  },
  {
    id: 'western-indian', name: 'Western Indian Ocean', shortName: 'West Indian Ocean', subtitle: 'Monsoon reefs & island chains',
    latitude: -11, longitude: 58, zoom: 4, habitats: ['Coral reefs', 'Atolls', 'Mangroves'],
    wildlife: ['Whale sharks', 'Manta rays', 'Sea turtles', 'Reef fish'],
    fact: 'UNEP identifies coral reefs as a connected ecological foundation across the Western Indian Ocean.',
    story: 'Monsoons reverse winds and currents across this broad region. Mainland coasts, volcanic islands and atolls can have very different visibility, productivity and encounter seasons.',
    source: 'UNEP Western Indian Ocean coral monitoring', url: 'https://www.unep.org/resources/report/western-indian-ocean-regional-coral-reef-monitoring-and-related-activities',
  },
  {
    id: 'eastern-indian', name: 'Eastern Indian Ocean', shortName: 'East Indian Ocean', subtitle: 'Remote reefs, ridges & deep plains',
    latitude: -20, longitude: 102, zoom: 4, habitats: ['Oceanic reefs', 'Seamounts & ridges', 'Deep-sea plains'],
    wildlife: ['Whale sharks', 'Manta rays', 'Sea turtles', 'Seabirds'],
    fact: 'Australia’s Indian Ocean Territories protect remote reef and deep-ocean habitat supporting more than 680 recorded fish species.',
    story: 'Indian and Pacific currents overlap around remote islands while the Western Australian margin drops through canyons into deep ocean. These widely separated habitats should not be treated as one local forecast.',
    source: 'Parks Australia — Indian Ocean Territories', url: 'https://parksaustralia.gov.au/news/securing-protection-indian-ocean-territories-marine-parks/',
  },
  {
    id: 'coral-triangle', name: 'Coral Triangle', shortName: 'Coral Triangle', subtitle: 'The global reef biodiversity center',
    latitude: 2, longitude: 125, zoom: 4, habitats: ['Coral reefs', 'Mangroves', 'Seagrass'],
    wildlife: ['Reef fish', 'Sea turtles', 'Manta rays', 'Marine mammals'],
    fact: 'NOAA reports nearly 600 coral species, more than 2,000 reef-fish species and six of seven sea-turtle species in the wider region.',
    story: 'Complex island geography links shallow reefs, deep passages and powerful currents. Conditions can change over very short distances, so this is a regional doorway rather than a site forecast.',
    source: 'NOAA Coral Reef Conservation Program', url: 'https://coralreef.noaa.gov/digital-corals/stories/jun20/coral-triangle/',
  },
  {
    id: 'great-barrier', name: 'Great Barrier Reef & Coral Sea', shortName: 'Great Barrier Reef', subtitle: 'Reefs, shoals & continental slope',
    latitude: -18, longitude: 151, zoom: 4, habitats: ['Coral reefs', 'Seagrass', 'Canyons & slopes'],
    wildlife: ['Reef fish', 'Dugongs', 'Sea turtles', 'Whales & dolphins'],
    fact: 'The Reef Authority documents more than 2,900 reefs, 1,625 fish species and over 450 hard-coral species.',
    story: 'The system extends across fourteen degrees of latitude and includes far more than coral: islands, seagrass, mangroves, deep channels and outer-shelf habitat all connect.',
    source: 'Great Barrier Reef Marine Park Authority', url: 'https://www.gbrmpa.gov.au/learn/biodiversity',
  },
  {
    id: 'central-pacific', name: 'Central Pacific Islands', shortName: 'Central Pacific', subtitle: 'Remote reefs & deep blue water',
    latitude: 17, longitude: -162, zoom: 3, habitats: ['Atolls', 'Coral reefs', 'Seamounts'],
    wildlife: ['Monk seals', 'Sea turtles', 'Sharks', 'Large reef fish'],
    fact: 'NOAA describes the Northwestern Hawaiian ecosystem as highly endemic, with coral reefs that remain dominated by sharks and large fish in protected areas.',
    story: 'Widely separated islands create small pockets of shallow habitat in a vast deep-ocean basin. Endemism and isolation make each archipelago distinct.',
    source: 'NOAA Papahānaumokuākea', url: 'https://www.fisheries.noaa.gov/pacific-islands/habitat-conservation/papahanaumokuakea-marine-national-monument',
  },
  {
    id: 'northwest-pacific', name: 'Northwest Pacific & Japan', shortName: 'Northwest Pacific', subtitle: 'Current boundaries from coral to kelp',
    latitude: 35, longitude: 142, zoom: 4, habitats: ['Kelp & rocky reefs', 'Coral reefs', 'Current fronts'],
    wildlife: ['Temperate reef fish', 'Sea turtles', 'Cetaceans', 'Pelagic fish'],
    fact: 'Japan’s environment ministry describes an unusually varied marine setting shaped by its long coastline, latitude, currents, depth and seafloor.',
    story: 'Cold and warm currents meet along a long island arc, connecting subarctic, temperate and subtropical systems. Local temperature and habitat can change rapidly across current fronts.',
    source: 'Ministry of the Environment, Japan', url: 'https://www.env.go.jp/nature/biodic/kaiyo-hozen/favor/favor05.html',
  },
  {
    id: 'new-zealand', name: 'Aotearoa & Southwest Pacific', shortName: 'Aotearoa', subtitle: 'Kelp, fiords & subantarctic water',
    latitude: -42, longitude: 177, zoom: 4, habitats: ['Kelp forests', 'Rocky reefs', 'Fiords & seamounts'],
    wildlife: ['Fur seals', 'Dolphins', 'Whales', 'Temperate reef fish'],
    fact: 'New Zealand DOC reports that almost half of the world’s cetacean species have been recorded in New Zealand waters.',
    story: 'Warm subtropical water meets cool subantarctic water around a long island chain. Kelp, shellfish beds, rocky reefs, soft sediment and deep features create strong habitat contrasts.',
    source: 'New Zealand Department of Conservation', url: 'https://www.doc.govt.nz/marinemammals',
  },
  {
    id: 'south-atlantic', name: 'South Atlantic', shortName: 'South Atlantic', subtitle: 'Oceanic islands & temperate shelves',
    latitude: -28, longitude: -20, zoom: 3, habitats: ['Open ocean', 'Island shelves', 'Upwelling margins'],
    wildlife: ['Cetaceans', 'Seabirds', 'Pelagic fish', 'Temperate reef life'],
    fact: 'This lens bridges warm subtropical gyres, productive continental margins and cooler southern waters.',
    story: 'The basin is intentionally generalized: the Benguela margin, Brazilian shelf and remote oceanic islands have very different communities and conditions.',
    source: 'FAO marine-area framework', url: 'https://www.fao.org/cwp-on-fishery-statistics/handbook/general-concepts/main-water-areas',
  },
  {
    id: 'arctic', name: 'Arctic Ocean', shortName: 'Arctic', subtitle: 'Sea ice & seasonal productivity',
    latitude: 76, longitude: -15, zoom: 2, habitats: ['Sea ice', 'Shallow shelves', 'Polar open water'],
    wildlife: ['Ice seals', 'Beluga & bowhead whales', 'Walrus', 'Arctic fish'],
    fact: 'NOAA describes ice algae and seasonal blooms as the foundation for food webs supporting fish, seals and whales.',
    story: 'Sea ice, daylight and water masses shape this ecosystem. Conditions change profoundly through the year, and a surface climatology cannot describe ice safety or navigation.',
    source: 'NOAA Ocean Service', url: 'https://oceanservice.noaa.gov/facts/smallestocean.html',
  },
  {
    id: 'southern-ocean', name: 'Southern Ocean', shortName: 'Southern Ocean', subtitle: 'Krill-powered polar ocean',
    latitude: -61, longitude: 25, zoom: 2, habitats: ['Sea ice edge', 'Polar shelves', 'Open ocean'],
    wildlife: ['Krill', 'Penguins', 'Seals', 'Baleen whales'],
    fact: 'The Australian Antarctic Program calls krill a cornerstone of the ecosystem, feeding fish, seabirds, seals and whales.',
    story: 'Seasonal ice and immense circumpolar currents connect the ocean around Antarctica. Surface temperature alone cannot convey its weather, ice or operational risk.',
    source: 'Australian Antarctic Program', url: 'https://www.antarctica.gov.au/about-antarctica/animals/food-web/',
  },
];
